# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.6.2"
selene = "Kampfkarren/selene@0.29.0"
rojo = "rojo-rbx/rojo@7.6.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.56.1"
StyLua = "JohnnyMorganz/StyLua@2.3.1"
pseudo-enum = "nightcycle/pseudo-enum@1.0.9"
file-to-luau = "nightcycle/file-to-luau@2.0.3"
darklua = "seaofvoices/darklua@0.17.2"
lune = "lune-org/lune@0.10.4"
